### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by pranavbhuv** [TheAz928/VanillaEnchantments#1]
Nice plugin!
Why can’t you just pull request this too pmmp?

**Comment by TheAz928** [comment]
It's in beta, bcz I don't know the actual damage values

**Comment by pranavbhuv** [comment]
Okay cool thanks for the plugin tho!

**Comment by TheAz928** [comment]
👍

**Comment by TheAz928** [comment]
Don't forget to star lol

**Comment by pranavbhuv** [comment]
Done
