### ISSUE TITLE
[01:02:11] [Server thread/CRITICAL]: Unhandled exception executing command 'kit axe' in kit: Call to undefined method pocketmine\entity\Effect::getEnchantmentByName() [01:02:11] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\entity\Effect::getEnchantmentByName()" (EXCEPTION) in "plugins/AdvancedKits-master/src/AdvancedKits/Kit" at line 114

### ISSUE THREAD

**Issue by XDqrkneZ** [TheAz928/VanillaEnchantments#11]
[01:02:11] [Server thread/CRITICAL]: Unhandled exception executing command 'kit axe' in kit: Call to undefined method pocketmine\entity\Effect::getEnchantmentByName()
[01:02:11] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\entity\Effect::getEnchantmentByName()" (EXCEPTION) in "plugins/AdvancedKits-master/src/AdvancedKits/Kit" at line 114

**Comment by TheAz928** [comment]
Invalid issue, my plugin is not related to that issue, #invalid_issue

**Comment by TheAz928** [comment]
Also I do not provide other plugin support here

**Comment by XDqrkneZ** [comment]
how come getenchantment by name or geteffectbyname not working?

**Comment by jasonw4331** [comment]
AdvancedKits loaded first

**Comment by XDqrkneZ** [comment]
??

**Comment by TheAz928** [comment]
I'm just providing help to stop your spamming​, the error is in AdvamcedKits, fix where it runs Effect::getEnchantmentByName instead of Effect::getEffectByName


Any other topic (About other plugin) is not allowed to discuss here
