### ISSUE TITLE
Add Enchantment Table and XP from ores

### ISSUE THREAD

**Issue by daniel022302** [TheAz928/VanillaEnchantments#13]
Can you make it so this will enable the enchanting table

**Comment by inxomnyaa** [comment]
Could you change the issue title to 'Add enchantment table' to be more descriptive? Thanks 👍

**Comment by Subject-4** [comment]
It would be pretty amazing to see the return of enchanting tables, considering that they've been useless for about a year now in pmmp ._.

**Comment by TheAz928** [comment]
I'll see how I can make enchanting transaction work without letting people duplicate, then I'll implement enchanting table

**Comment by TheAz928** [comment]
This project will be done by this month, xp is done by pmmp already. Just need to implement enchantment table.
