### ISSUE TITLE
Lag Spike

### ISSUE THREAD

**Issue by SpecialistNinja** [TheAz928/VanillaEnchantments#16]
I tested it out on the latest version (breakable armor)

When you wear protection armor and walk up to the cactus or lava you immediately get fps lag spike

When you don't wear any armor and walk up to the cactus or lava you don't get fps lag spike

I tried test it on the version without breakable armor and it work fine, no lag spike at all

**Comment by inxomnyaa** [comment]
"fps" is client related. Have you tested the same thing in singleplayer?

**Comment by SpecialistNinja** [comment]
I already did test the old version without breakable armor but when i update it to the version with breakable armor i got the fps lag. I even tested it on a clean server that have no plugin except Vanilla Enchant

**Comment by TheAz928** [comment]
I don't think this plugin is anyway related to fps

**Comment by inxomnyaa** [comment]
It could create a slight issue if it would move or modify the player, but changing the armor durability basically SHOULD not make the client lag. It could be that the client tries to send a ton of shit though, i guess i will bug someone from mojang about that if i can reproduce the issue.

**Comment by AydarTop** [comment]
@thebigsmileXD I can reproduce this issue. Damage reduce implemented wrongly
