### ISSUE TITLE
Damage cooldown is reduced to 0

### ISSUE THREAD

**Issue by inxomnyaa** [TheAz928/VanillaEnchantments#22]
Whilest having any enchantments on the armor, your hit-delay is 0

Example: Lava instantly kills you, and magma blocks hit you every tick

**Comment by nasiridrishi** [comment]
@thebigsmileXD and when players suffocate in blocks!

**Comment by inxomnyaa** [comment]
Oh also, this issue relates to #16 , the client starts to lag because the damage + armor updates come too fast

**Comment by TheAz928** [comment]
@thebigsmileXD any ideas how to fix?

**Comment by inxomnyaa** [comment]
I remember that i had the same bug back in old days, but that is over a year ago, so.. not really

**Comment by inxomnyaa** [comment]
Rest in piece all the formatting fixes i just applied in the pr..

**Comment by inxomnyaa** [comment]
I just saw how you check the cooldown.. why not using player -> cooldown? afair entities have a cooldown coded into them

**Comment by TheAz928** [comment]
Sorry I mistakenly uploaded file instead of edit xD

**Comment by inxomnyaa** [comment]
Well, PHPDoc comments are still not correct. Here are reasons:
- no valid `@return` tag
- return tag fixes i made are gone
- no `@param`
- invalid formatting

Also, `int` became `Int` again, it is just common to write them in lowercase
