### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tbhDequan** [TheAz928/VanillaEnchantments#25]
16.12 14:55:11 [Server] Server thread/CRITICAL Error: "Undefined class constant 'CAUSE_EXPLOSION'" (EXCEPTION) in "VanillaEnchantments_v2.0.0-dev/src/VanillaEnchantments/handlers/BlastProtection" at line 22

**Comment by inxomnyaa** [comment]
duplicate of https://github.com/TheAz928/VanillaEnchantments/issues/18
