### ISSUE TITLE
Add Max Level

### ISSUE THREAD

**Issue by DrNoct** [TheAz928/VanillaEnchantments#28]
Can you add max level on the enchantments?

**Comment by TheAz928** [comment]
I'm not entirely sure about the max level values, so currently no, also I did setup some max level values even some are wrong

**Comment by DrNoct** [comment]
oh oke no problem dude.
before update plugin advancedkits and vanillaenchant i can use advancedkit normaly with enchant from vanilla enchant. but now i can't use kit with vanillaenchant again. can u help me? thx

**Comment by TheAz928** [comment]
Basically, your advkits plugin outdated
