### ISSUE TITLE
PMMP Added enchantment Protection

### ISSUE THREAD

**Issue by udachin26** [TheAz928/VanillaEnchantments#31]
PMMP core added enchant. protection. Remove from plugin this enchant!
sorry, i'm russian

**Comment by inxomnyaa** [comment]
wasnt that already done just recently?

**Comment by udachin26** [comment]
I was looking for this change in the plugin, but I could not find it! Can you show me?
@thebigsmileXD

**Comment by udachin26** [comment]
Why did you close the issue?
@TheAz928

**Comment by inxomnyaa** [comment]
I was wrong -> https://github.com/TheAz928/VanillaEnchantments/commit/dc19da8ceff595cb16ec935e82775c693d3571f2 did not remove protection
