### ISSUE TITLE
the plugin wont load any enchants 

### ISSUE THREAD

**Issue by timbersquirrel** [TheAz928/VanillaEnchantments#4]
i am using the alpha 8 version of pocketmine: https://github.com/pmmp/PocketMine-MP/releases
i dont know if it needs a newer version for enchants to properly register but they wont on this version please help me, thanks.

**Comment by TheAz928** [comment]
You need to use ALPHA9

**Comment by timbersquirrel** [comment]
Can you send me the link to download alpha 9?

**Comment by TheAz928** [comment]
Use this one I use, but the API is changed to 8 in this phar in case you don't have to update all plugins lol https://www.mediafire.com/download/dbum45z948myb7p

**Comment by timbersquirrel** [comment]
Thanks
