### ISSUE TITLE
Protection

### ISSUE THREAD

**Issue by austina1212** [TheAz928/VanillaEnchantments#42]
So, I have tested a few protection levels from no enchant to protection 50 and they all seem to not work at all... I am running PMMP Alpha 11, any ideas why?

**Comment by TheAz928** [comment]
pmmp should have protection implemented

**Comment by austina1212** [comment]
@TheAz928 it doesn't.... Any ideas on how to fix this?... Also if you didn't know, this is iRainDrop lmfao

**Comment by TheAz928** [comment]
Lmfao

**Comment by austina1212** [comment]
@TheAz928 ?

**Comment by FaanMaario** [comment]
I can confirm, protection enchants doesn't work correctly

**Comment by TDMidkwhatisxd** [comment]
still not working
