### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [TheAz928/VanillaEnchantments#43]
15:04:20 CRITICAL > Could not execute task vanilla\DamageArmorTask: Undefined offset: 444
15:04:20 CRITICAL > ErrorException: "Undefined offset: 444" (EXCEPTION) in "plugins/VanillaEnchantments-master/src/vanilla/Core" at line 179
15:04:20 DEBUG > #0 plugins/VanillaEnchantments-master/src/vanilla/Core(179): pocketmine\error_handler(integer 8, string Undefined offset: 444, string /root/pm/plugins/VanillaEnchantments-master/src/vanilla/Core.php, integer 179, array Array())
15:04:20 DEBUG > #1 plugins/VanillaEnchantments-master/src/vanilla/Core(247): vanilla\Core->damageChestplate(pocketmine\Player object, integer 15)
15:04:20 DEBUG > #2 plugins/VanillaEnchantments-master/src/vanilla/DamageArmorTask(98): vanilla\Core->useArmors(pocketmine\Player object, integer 15)
15:04:20 DEBUG > #3 src/pocketmine/scheduler/TaskHandler(160): vanilla\DamageArmorTask->onRun(integer 36881)
15:04:20 DEBUG > #4 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 36881)
15:04:20 DEBUG > #5 src/pocketmine/Server(2610): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 36881)
15:04:20 DEBUG > #6 src/pocketmine/Server(2352): pocketmine\Server->tick()
15:04:20 DEBUG > #7 src/pocketmine/Server(2225): pocketmine\Server->tickProcessor()
15:04:20 DEBUG > #8 src/pocketmine/Server(1809): pocketmine\Server->start()
15:04:20 DEBUG > #9 src/pocketmine/PocketMine(385): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/pm/, string /root/pm/plugins/)

**Comment by TheAz928** [comment]
You're using TeaSpoon if I'm correct, and elytra method isn't Implemented

**Comment by shdudwns** [comment]
I do not using Teaspoon
@TheAz928

**Comment by TheAz928** [comment]
It's related to elytra damage which is not Implemented

**Comment by shdudwns** [comment]
Does not Altay support it?

**Comment by TheAz928** [comment]
This is now fixed on latest pmmp builds (743 and up)
