### ISSUE TITLE
OP Knockback?

### ISSUE THREAD

**Issue by Ben420** [TheAz928/VanillaEnchantments#48]
I have protection 1 on armour and I got someone with a sharpness 1 sword, and I go flying in the air? Any idea?

**Comment by TheAz928** [comment]
I don't see anything wrong with this plugin.
Check your other knock back related plugins, also to clarify that the issue is from this plugin or not, test it on a server with only this plugin installed, thank you.

**Comment by Ben420** [comment]
It was tested on my test server with just this plugin. If it has a custom enchant on sword, there is a OP knockback on it, without the custom enchants its fine.
