### ISSUE TITLE
Please fix this error.

### ISSUE THREAD

**Issue by yunseo2723** [TheAz928/VanillaEnchantments#59]
If you hit a user with an enchant knife, the console will fail.
<img width="943" alt="zxc" src="https://user-images.githubusercontent.com/25340054/42124069-764aaf46-7c97-11e8-8554-4d72e5db8e6c.PNG">

**Comment by TheAz928** [comment]
Update your PocketMine-MP to 3.0.x release (recommend 3.0.3+)
