### ISSUE TITLE
 There are not some enchant codes.

### ISSUE THREAD

**Issue by yunseo2723** [TheAz928/VanillaEnchantments#61]
<img width="536" alt="31" src="https://user-images.githubusercontent.com/25340054/42259336-05c3b158-7f9b-11e8-9368-dda3a01358b4.PNG">
There are some enchant codes.
For example, code 5, 6, 7, 8, 9 appears to be missing.
I am using PMMP3.0.4.

**Comment by MSG100TC** [comment]
Sharpness is supposed to be 9 and it isn't there...

**Comment by YHC2538** [comment]
Use latest version...

**Comment by YHC2538** [comment]
I can only see fire_aspect and knockback not working
