### ISSUE TITLE
Knockback and fire_aspect enchant isn't working

### ISSUE THREAD

**Issue by YHC2538** [TheAz928/VanillaEnchantments#64]
It's not working when you try to use those enchants.
It just says "There's no such Enchantment ID as (Number)"

**Comment by YHC2538** [comment]
@TheAz928

**Comment by TheAz928** [comment]
support is pending, I'm trying to make this plugin compatible with 1.5

**Comment by YHC2538** [comment]
Thank you 👍

**Comment by YHC2538** [comment]
Any updates for kock back and fire aspect enchant?
