### ISSUE TITLE
Altay 1.2 Version not working!

### ISSUE THREAD

**Issue by many1337** [TheAz928/VanillaEnchantments#66]
15:53:21 CRITICAL > pocketmine\plugin\PluginException: "pocketmine\event\entity\EntityDamageByEntityEvent does not have a valid handler list" (EXCEPTION) in "src/pocketmine/plugin/PluginManager" at line 811
15:53:21 DEBUG > #0 src/pocketmine/plugin/PluginManager(785): pocketmine\plugin\PluginManager->registerEvent(string pocketmine\event\entity\EntityDamageByEntityEvent, vanilla\Core object, integer 3, pocketmine\plugin\MethodEventExecutor object, vanilla\Core object, boolean 1)
15:53:21 DEBUG > #1 plugins/VanillaEnchantments-master/src/vanilla/Core(68): pocketmine\plugin\PluginManager->registerEvents(vanilla\Core object, vanilla\Core object)
15:53:21 DEBUG > #2 src/pocketmine/plugin/PluginBase(90): vanilla\Core->onEnable()
15:53:21 DEBUG > #3 src/pocketmine/plugin/FolderPluginLoader(126): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
15:53:21 DEBUG > #4 src/pocketmine/plugin/PluginManager(583): pocketmine\plugin\FolderPluginLoader->enablePlugin(vanilla\Core object)
15:53:21 DEBUG > #5 src/pocketmine/Server(1977): pocketmine\plugin\PluginManager->enablePlugin(vanilla\Core object)
15:53:21 DEBUG > #6 src/pocketmine/Server(1963): pocketmine\Server->enablePlugin(vanilla\Core object)
15:53:21 DEBUG > #7 src/pocketmine/Server(1757): pocketmine\Server->enablePlugins(integer 1)
15:53:21 DEBUG > #8 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string D:\marko\OldMaster\OPKitPvP\, string D:\marko\OldMaster\OPKitPvP\plugins\)

**Comment by artulloss** [comment]
don't open issues regarding forks
