### ISSUE TITLE
These enchantments don't work

### ISSUE THREAD

**Issue by FearRec** [TheAz928/VanillaEnchantments#67]
The enchantments below display an error, when you try to enchant tools and amour using the command "/enchant". The error is, "There is no such enchantment with ID {number}":

1. Thorns
2. Depth strider
3. Aqua affinity
4. Bane of athropods
5. Knockback
6. Fire aspect
7. Flame
8. Infinity
9. Mending

**Comment by Haxley** [comment]
Can confirm for knockback, fire, flame, infinity.

**Comment by TheAz928** [comment]
Seems like I've been getting "4.0.0" dev notifications, I thought these were done in 3.1.x but after I carefully seeing the messages, it's actually for 4.0.0, that's why I removed support for those enchantments. Will add those back soon.
