### ISSUE TITLE
Enchant Effects!

### ISSUE THREAD

**Issue by nasiridrishi** [TheAz928/VanillaEnchantments#7]
there are lots of problem regarding abilities of enchants .. I have made enchant shop using command shop and players can even enchant sticks, bows(knock back, sharpness) and they are too powerful, it kills u in 2 hits only no matter if u have best enchants armors and eating enchanted golden apples. power enchants has got problems.. knock back  have too much power. players can enchant stuffs which should not!!

**Comment by jasonw4331** [comment]
The client handles Enchantment distribution with enchantment tables, this plugin only registers the enchantments server-side and implements them.

**Comment by nasiridrishi** [comment]
so! it shoud not enchant/register enchant on wrong items like protection on stick!?

**Comment by TheAz928** [comment]
Use latest release, this issue is now closed
